### PR TITLE
Sign in dashboard

### LINKED ISSUE #39: Add log out
To do this we will need both the logout button as well as the code to log out and the code to toggle which buttons are being seen. Use Firebase method on authStateChange().

### PR DESCRIPTION
**Pull request by andy7809**
This PR adds the user dashboard functionality to the website front end. If the user is logged in, the logout button is displayed. If the user if not logged in, the option to login or sign up is displayed. This state changes when auth changes in the firebase API.

### CODE REVIEW

**Comment by andy7809** [comment]
Need consent from @emmapaczkowski

**Review by PriyaVarra — COMMENTED** [review]
Looks good! Only suggestion would be to add documentation to the newly added functions

**Comment by andy7809** [comment]
Will do, that's the next job

**Review by wjiamin — COMMENTED** [review]
LGTM

**Comment by andy7809** [comment]
Hey @emmapaczkowski, if you could consent to this I will merge it. Thanks!

**Comment by saileshsimhadri** [comment]
LGTM

**Pull request merged**
